### ISSUE TITLE
help install

### ISSUE THREAD

**Issue by skyvxl** [notohh/snowflake#20]
hi, im newbie. can you tell me how to install your config?

**Comment by notohh** [comment]
hi!

my config makes a lot of assumptions that are specific for my usecases (i.e directories being in certain places, secrets, etc), so it'd probably be pretty tough just to clone & install and have it work out of the box.

instead, i'd recommend looking into some [nix starter configs](https://github.com/Misterio77/nix-starter-configs) for some boilerplate, then cherry pick from my repo & others. this will probably be a lot easier in the long run, and it'll get you familiar with nix along the way.

of course, you can also just `git clone https://github.com/notohh/snowflake.git` and then `sudo nixos-rebuild --flake .#the-host-you-want`, but i doubt it will work out of the box like i stated above.

**Comment by skyvxl** [comment]
i see thanks
