### ISSUE TITLE
Blocky

### ISSUE THREAD

**Issue by ldnora** [notohh/snowflake#21]
Hi!

You use the Blocky at the file hosts/haru/services/blocky.nix. What's your tutorial you use to install and configure it? I'm tryning to use it, but don't work.

**Comment by notohh** [comment]
hey!

i just followed the [configuration docs](https://0xerr0r.github.io/blocky/v0.23/configuration/) on blockys site, and then just wrote the options in nix. since its configured with `yaml`, its relatively easy

what isnt working for you specifically?

**Comment by ldnora** [comment]
Hey bro!

Ok. 

It don't block the blacklist. I only followed the [basic nix configuration example](https://nixos.wiki/wiki/Blocky). 

If you want see my blocky.nix, is [here](https://github.com/Leandro-Dalla-Nora/nixos-config/blob/main/modules/nixos/blocky.nix).

**Comment by notohh** [comment]
sorry for the late reply, got busy!

make sure 53 is open for both udp and tcp, everything else looks fine? so it should work. make sure you also switch over your DNS to blocky on your router, or per device
